import { useState, useEffect } from "react";
import { Card, FormField, Loader } from "../components";

type propType = {
  title: string;
  data: Array<object>;
};

const RenderCard = (props: propType): JSX.Element => {
  const { data, title } = props;
  if (data && data.length > 0) {
    return (
      <>
        {data.map((post: object) => (
          <Card />
        ))}
      </>
    );
  }
  return (
    <h2 className="mt-5 font-bold text-[#6449ff] text-xl uppercase">{title}</h2>
  );
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPost, setAllPost] = useState([]);
  const [search, setSearch] = useState("");

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">
          The Community Showcase
        </h1>
        <p>
          Browser through a collection of imaginative and visually stunning
          images generated by the DALL-E AI.
        </p>
      </div>
      <div className="mt-10">
        <FormField />
      </div>
      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {search && (
              <h2 className="font-medium text-[#666e75] text-xl mb-3">
                Showing results for{" "}
                <span className="text-[#222328]">{search}</span>
              </h2>
            )}
            <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {search ? (
                <RenderCard title="No search results found" data={[]} />
              ) : (
                <RenderCard title="No posts found" data={[]} />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
